### ISSUE TITLE
[PC] 共通 - 左上のSVGロゴの高さがスクロールに伴って変わる

### ISSUE THREAD

**Issue by sshono1210** [chatbox-inc/cb_works2018#29]
![screen shot 2018-02-23 at 17 26 32](https://user-images.githubusercontent.com/16553978/36584836-bc5367b8-18be-11e8-8a0c-822431b6b9e3.png)

↓

![screen shot 2018-02-23 at 17 26 08](https://user-images.githubusercontent.com/16553978/36584806-a9927862-18be-11e8-8595-d619205c3c17.png)

スクロールすると微妙に高さが伸びる。
（問い合わせフォームのページでも起こります）

**Comment by yasui05821** [comment]
@sshono1210 
ディスプレイサイズが1920×1200以上になる場合にのみバグが再現される気がします。

特殊な環境でのみおこるバグか確認したいので、
ディスプレイサイズを調整するアプリを切っている状態でも再現できるかご確認お願いします。
