### ISSUE TITLE
マルチブラウザチェック

### ISSUE THREAD

**Issue by yasui05821** [chatbox-inc/cb_works2018#41]
http://works.chatbox-inc.com/

【PC】
- [x] chrome
- [x] safari
- [x] Firefox
- [x] edge(多少の崩れはOK)

【スマホ】
- [x] iphone
- [x] Android

**Comment by tyokinuhata** [comment]
@yasui05821 
chrome, safari, FireFoxは問題無さそうでした.
なお, Androidはchromeで検証し, 問題点はissueを立てました(#43).
