### ISSUE TITLE
【超優先】PC閲覧時のヒーローセクション

### ISSUE THREAD

**Issue by yasui05821** [chatbox-inc/cb_works2018#9]
<img width="1612" alt="2017-12-18 13 20 08" src="https://user-images.githubusercontent.com/13504241/34089840-5ae1062c-e3f6-11e7-90a5-dbe7de39530a.png">

画面サイズが大きい時、画像の上に重ねている赤いオーバーレイが切れてしまうので実装見直し

**Comment by kaaai** [comment]
対応済みのためclose
